### ISSUE TITLE
recurrent events

### ISSUE THREAD

**Issue by RosaMGini** [ARS-toscana/ECVM#9]
to be added

**Comment by RosaMGini** [comment]
Generalised convulsion  - 30 days
Anaphylaxis - 30 days

**Comment by DavideMessinaARS** [comment]
I checked CountPersonTime and it doesn't seem possible to mix recurrent and not recurrent events together.

Should I set the `Rec_period` for not recurrent event to a high enough number? (9999 for example)

**Comment by DavideMessinaARS** [comment]
Added in version 3.5
